services:
  - type: web
    name: whatsapp-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    cronJobs:
      - name: daily-message
        schedule: "0 8 * * *"
        command: node index.js 